export type DefaultTimelineItem = {
  id: string;
  title: string;
  description: string;
  owner: string;
  date: string;
  category: string;
  isCritical: boolean;
  isCompleted: boolean;
};

export const INITIAL_TIMELINE: DefaultTimelineItem[] = [
  {
    id: "0",
    title: "Hotel Deposit Secured",
    description:
      "5,000 RMB advance paid to secure conference hall and accommodation credit.",
    owner: "Financial Secretary + Treasurer",
    date: "2026-03-13",
    category: "finance",
    isCritical: true,
    isCompleted: true,
  },
  {
    id: "1",
    title: "Conference Chair Appointed",
    description: "Ad hoc committee leadership established for LSUIC 2026.",
    owner: "National President",
    date: "2026-04-06",
    category: "governance",
    isCritical: true,
    isCompleted: true,
  },
  {
    id: "2",
    title: "First Committee Meeting Completed",
    description:
      "Kickoff completed with agenda, committee structure, and action points.",
    owner: "Chair + Secretary",
    date: "2026-04-10",
    category: "governance",
    isCritical: true,
    isCompleted: true,
  },
  {
    id: "2a",
    title:
      "Wave 1 Confirmation Hearing Completed (Chair, Vice-Chair, Secretary, PRO/Media)",
    description:
      "First four leadership positions were confirmed; records updated for meeting follow-up.",
    owner: "Chair + Council of Coordinators (CoC)",
    date: "2026-04-14",
    category: "governance",
    isCritical: true,
    isCompleted: true,
  },
  {
    id: "2b",
    title:
      "Wave 2 Confirmation Hearing (Cooking, Logistics, Sports, Decoration)",
    description:
      "Remaining committee leads present progress and complete hearing requirements.",
    owner: "Chair + Council of Coordinators (CoC) + Remaining Committee Leads",
    date: "2026-04-15",
    category: "governance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "2c",
    title: "Thursday Meeting Runbook Executed",
    description:
      "Use standard flow: Opening Prayer, committee reports, decision gate, action lock, AOB, Closing Prayer.",
    owner: "Chair + Secretary",
    date: "2026-04-16",
    category: "governance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "2d",
    title: "Publicity Sprint Starts",
    description:
      "Begin immediate publicity campaign after the Thursday meeting with daily execution for 3 days.",
    owner: "PRO / Media + Committee Chairs",
    date: "2026-04-16",
    category: "program",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "2e",
    title: "Media Venue Storytelling Pack Approved",
    description:
      "Media finalizes short video and photo storyline showing on-ground facilities: Gym, Swimming Pool, Dining Hall, Conference Hall, Dinner Hall, and Hotel Yard using assets from scripts/conference-2026/images and scripts/conference-2026/ocr.",
    owner: "PRO / Media + Logistics",
    date: "2026-04-17",
    category: "program",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "2f",
    title: "Conference Fee and Payment Terms Finalized",
    description:
      "Lock fee amount and payment instructions before signup link goes public.",
    owner: "Chair + Financial Secretary + Treasurer",
    date: "2026-04-18",
    category: "finance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "3",
    title: "Signup Link and QR Flyer Published (After 3-Day Publicity)",
    description:
      "Release registration flyer and delegate signup link after publicity momentum is established.",
    owner: "PRO / Media + Secretary",
    date: "2026-04-19",
    category: "registration",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "4",
    title: "Disbursement SLA Published",
    description:
      "Funding requests must be released within 24-48 hours after approval.",
    owner: "Treasurer + Financial Secretary",
    date: "2026-04-18",
    category: "finance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "5",
    title: "Subcommittee Channels Activated",
    description:
      "Every committee group is created with Chair, Co-Chair, and Secretary included.",
    owner: "All Committee Leaders",
    date: "2026-04-19",
    category: "governance",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "6",
    title: "Master Task Board Published",
    description:
      "One workplan with responsible lead, due date, risk, and status for every committee output.",
    owner: "Secretary + Chair",
    date: "2026-04-21",
    category: "governance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "7",
    title: "Budget Drafts Submitted",
    description: "Committee leads submit first pass budget for 170 delegates.",
    owner: "Cooking, Logistics, Program, Media, Sports",
    date: "2026-04-24",
    category: "finance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "8",
    title: "Conference Fee Structure Finalized",
    description:
      "Fee tiers and payment policy approved from RMB 275 baseline, including a lower-price option if budget permits.",
    owner: "Chair + Finance Team",
    date: "2026-04-25",
    category: "finance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "9",
    title: "Budget Defense and Approval Gate",
    description:
      "Consolidated budget defended and signed off with CoC alignment.",
    owner: "Chair + Treasurer + Financial Secretary",
    date: "2026-04-28",
    category: "finance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "10",
    title: "Registration Window and Payment Channels Announced",
    description:
      "Public release of registration form, fee policy, payment instructions, and approval expectations.",
    owner: "Secretary + Media",
    date: "2026-05-01",
    category: "registration",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "11",
    title: "Media Wave 2 - Signup Push",
    description:
      "Second promotion pack drives signups with highlights, testimonials, and weekly countdown posts.",
    owner: "PRO / Media",
    date: "2026-05-03",
    category: "program",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "12",
    title: "Rooming and Roommate Selection Rules Locked",
    description:
      "Finalize roommate choice process, single-room rules, and accommodation assignment workflow.",
    owner: "Logistics Lead",
    date: "2026-05-08",
    category: "logistics",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "13",
    title: "Transport Plan v1",
    description: "Inter-city arrival support and local route plan drafted.",
    owner: "Logistics + Sports",
    date: "2026-05-12",
    category: "logistics",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "14",
    title: "Mid-Point Readiness Review",
    description: "Cross-committee checkpoint with risk and blocker escalation.",
    owner: "Chair + Co-Chair",
    date: "2026-05-15",
    category: "governance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "15",
    title: "Menu and Procurement Plan v1",
    description:
      "Meal-by-day plan, quantity model, and dietary handling approved.",
    owner: "Cooking Chair + Team",
    date: "2026-05-18",
    category: "logistics",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "16",
    title: "Panel and Program Topics Final",
    description:
      "Program sequence and speaking sessions frozen for publication.",
    owner: "Program Lead + Secretary",
    date: "2026-05-29",
    category: "program",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "17",
    title: "Awards Criteria Approved",
    description: "Awards categories, scoring, and host flow finalized.",
    owner: "Awards/Program + Media",
    date: "2026-06-02",
    category: "program",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "18",
    title: "Election Operations Plan Signed",
    description:
      "IEC coordination, campaign timeline, voting and certification flow fixed.",
    owner: "Secretary + IEC Liaison",
    date: "2026-06-05",
    category: "governance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "19",
    title: "Program Finalization Gate",
    description: "All plenary, elections, sports, and awards slots time-boxed.",
    owner: "Chair + Program Lead",
    date: "2026-06-12",
    category: "program",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "20",
    title: "Print and Branding Freeze",
    description:
      "Booklets, badges, tags, T-shirts, and banners locked for production.",
    owner: "Media + Logistics",
    date: "2026-06-20",
    category: "logistics",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "21",
    title: "Registration Closes",
    description:
      "Final delegate list, payment reconciliation, and rooming base frozen.",
    owner: "Registration + Finance",
    date: "2026-06-22",
    category: "registration",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "22",
    title: "Final Vendor Payments Complete",
    description: "Critical venue, transport, and procurement payments cleared.",
    owner: "Treasurer + Financial Secretary",
    date: "2026-06-24",
    category: "finance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "23",
    title: "Operational Dry Run",
    description:
      "Registration desk, transport handoff, and session transitions rehearsed.",
    owner: "Logistics + Program",
    date: "2026-06-26",
    category: "logistics",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "24",
    title: "Go/No-Go Decision Meeting",
    description: "Final readiness vote with contingency activation if needed.",
    owner: "Chair + CoC Leadership",
    date: "2026-06-28",
    category: "governance",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "25",
    title: "Arrival Briefing Pack Released",
    description:
      "Final delegate travel guidance, check-in details, and day-1 brief sent before July.",
    owner: "Secretary + Logistics + Media",
    date: "2026-06-29",
    category: "registration",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "25b",
    title: "Manual Correction Window Opens",
    description:
      "July is reserved for manual fixes, contingency handling, and resolving flagged issues only.",
    owner: "Chair + All Committee Leads",
    date: "2026-07-01",
    category: "governance",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "26",
    title: "Onsite Setup Day",
    description:
      "Venue setup, signage, technical checks, and material staging.",
    owner: "Logistics + Media",
    date: "2026-07-22",
    category: "event",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "27",
    title: "Conference Day 1 - Arrival and Opening",
    description:
      "Delegate check-in, opening formalities, and initial sessions.",
    owner: "Chair + Secretariat",
    date: "2026-07-23",
    category: "event",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "27a",
    title: "Welcome and Meet-and-Greet Party",
    description:
      "Host delegates and invited guests for official networking and orientation.",
    owner: "Program + Media + Logistics",
    date: "2026-07-23",
    category: "event",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "28",
    title: "Conference Day 2 - Proceedings and Elections",
    description:
      "Reports, campaigns, voting operations, and election announcements.",
    owner: "Program + IEC + Secretariat",
    date: "2026-07-24",
    category: "event",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "29",
    title: "Conference Day 3 - Independence and Sports",
    description: "Independence program, certification, and sports activities.",
    owner: "Program + Sports",
    date: "2026-07-25",
    category: "event",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "29a",
    title: "Pool Party and Recreation Session",
    description:
      "Hotel pool networking block with controlled safety and media coverage plan.",
    owner: "Sports + Logistics + Media",
    date: "2026-07-25",
    category: "event",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "30",
    title: "Achievers Awards Night and Inaugural Ball",
    description:
      "Awards delivery, crowning flow, and formal evening program with full media capture.",
    owner: "Program + Media + Logistics",
    date: "2026-07-26",
    category: "event",
    isCritical: false,
    isCompleted: false,
  },
  {
    id: "31",
    title: "Conference Closeout and Departure",
    description:
      "Final delegate support, venue handover, and closure activities.",
    owner: "Logistics + Secretariat",
    date: "2026-07-27",
    category: "event",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "32",
    title: "Committee Activity Report Submitted",
    description:
      "Comprehensive conference report delivered to CoC and executive leadership within one week.",
    owner: "Chair + Secretary",
    date: "2026-08-03",
    category: "post-event",
    isCritical: true,
    isCompleted: false,
  },
  {
    id: "33",
    title: "Post-Conference Audit Completed",
    description:
      "Financial audit and reconciled expenditure records finalized.",
    owner: "Financial Secretary + Treasurer",
    date: "2026-08-27",
    category: "post-event",
    isCritical: true,
    isCompleted: false,
  },
];
