/**
 * JICF Wedding Certificate — landscape official marriage record.
 * Palette matches Certificate of Service (navy, red, gold, cream).
 */

import type { CertificateTemplate } from "../types";
import { JICF_COLORS, JICF_FONTS, JICF_ORG_INFO } from "./constants";

const CREAM = "#fffde7";
const IVORY = "#fffef8";

export const jicfWeddingCertificate: CertificateTemplate = {
  id: "jicf-wedding-certificate",
  name: "JICF Wedding Certificate",
  description:
    "Official landscape marriage certification for Jinan International Christian Fellowship",
  organization: "jicf",
  category: "wedding",
  elements: [
    {
      id: "page-ivory",
      type: "rectangle",
      content: "",
      position: { x: 0, y: 0, width: 1200, height: 838 },
      style: { backgroundColor: IVORY },
    },
    {
      id: "outer-border",
      type: "rectangle",
      content: "",
      position: { x: 22, y: 22, width: 1156, height: 794 },
      style: {
        backgroundColor: "transparent",
        borderColor: JICF_COLORS.primary,
        borderWidth: 6,
        borderStyle: "solid",
      },
    },
    {
      id: "gold-border",
      type: "rectangle",
      content: "",
      position: { x: 36, y: 36, width: 1128, height: 766 },
      style: {
        backgroundColor: CREAM,
        borderColor: JICF_COLORS.gold,
        borderWidth: 2,
        borderStyle: "solid",
      },
    },
    {
      id: "inner-border",
      type: "rectangle",
      content: "",
      position: { x: 48, y: 48, width: 1104, height: 742 },
      style: {
        backgroundColor: IVORY,
        borderColor: JICF_COLORS.secondary,
        borderWidth: 2,
        borderStyle: "solid",
      },
    },
    {
      id: "jicf-logo",
      type: "image",
      content: "/JICF_LOGO1.png",
      position: { x: 72, y: 64, width: 78, height: 78 },
      style: { objectFit: "contain" },
    },
    {
      id: "seal-disc",
      type: "rectangle",
      content: "",
      position: { x: 1050, y: 64, width: 78, height: 78 },
      style: {
        backgroundColor: JICF_COLORS.primary,
        borderColor: JICF_COLORS.gold,
        borderWidth: 3,
        borderStyle: "solid",
        borderRadius: 39,
      },
    },
    {
      id: "seal-cross",
      type: "text",
      content: "✝",
      position: { x: 1050, y: 78, width: 78, height: 50 },
      style: {
        fontSize: 36,
        color: JICF_COLORS.gold,
        textAlign: "center",
      },
    },
    {
      id: "organization-name",
      type: "text",
      content: JICF_ORG_INFO.name.toUpperCase(),
      position: { x: 170, y: 68, width: 860, height: 40 },
      style: {
        fontSize: 24,
        fontFamily: JICF_FONTS.elegant,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "center",
        letterSpacing: "1.5px",
      },
    },
    {
      id: "subtitle",
      type: "text",
      content: "Official Marriage Certification",
      position: { x: 170, y: 110, width: 860, height: 26 },
      style: {
        fontSize: 16,
        fontFamily: JICF_FONTS.secondary,
        fontStyle: "italic",
        fontWeight: "600",
        color: JICF_COLORS.secondary,
        textAlign: "center",
      },
    },
    {
      id: "certificate-title",
      type: "text",
      content: "WEDDING CERTIFICATE",
      position: { x: 80, y: 158, width: 1040, height: 48 },
      style: {
        fontSize: 38,
        fontFamily: JICF_FONTS.elegant,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "center",
        letterSpacing: "3px",
      },
    },
    {
      id: "title-rule",
      type: "rectangle",
      content: "",
      position: { x: 390, y: 212, width: 420, height: 3 },
      style: {
        backgroundColor: JICF_COLORS.accent,
        borderRadius: 2,
      },
    },
    {
      id: "certification-text",
      type: "text",
      content:
        "This is to certify that on the {{ceremonyDay}} day of {{ceremonyMonth}}, {{ceremonyYear}}, a sacred marriage ceremony was solemnly officiated and completed in {{location}}.",
      position: { x: 90, y: 228, width: 1020, height: 48 },
      style: {
        fontSize: 16,
        fontFamily: JICF_FONTS.primary,
        color: JICF_COLORS.black,
        textAlign: "center",
        lineHeight: 1.45,
      },
    },
    {
      id: "oversight-text",
      type: "text",
      content:
        "The holy matrimony was celebrated under the authority and pastoral oversight of Jinan International Christian Fellowship, uniting the below two persons in lawful and sacred marriage before God and witnesses.",
      position: { x: 90, y: 278, width: 1020, height: 48 },
      style: {
        fontSize: 15,
        fontFamily: JICF_FONTS.primary,
        color: JICF_COLORS.darkGray,
        textAlign: "center",
        lineHeight: 1.45,
      },
    },
    {
      id: "parties-band",
      type: "rectangle",
      content: "",
      position: { x: 90, y: 336, width: 1020, height: 110 },
      style: {
        backgroundColor: "#fff6c8",
        borderColor: JICF_COLORS.gold,
        borderWidth: 1,
        borderStyle: "solid",
      },
    },
    {
      id: "bride-label",
      type: "text",
      content: "BRIDE",
      position: { x: 110, y: 346, width: 420, height: 20 },
      style: {
        fontSize: 12,
        fontFamily: JICF_FONTS.secondary,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "center",
        letterSpacing: "3px",
      },
    },
    {
      id: "bride-name",
      type: "text",
      content: "{{brideName}}",
      position: { x: 110, y: 368, width: 420, height: 62 },
      style: {
        fontSize: 26,
        fontFamily: JICF_FONTS.script,
        fontWeight: "bold",
        fontStyle: "italic",
        color: JICF_COLORS.secondary,
        textAlign: "center",
      },
    },
    {
      id: "parties-and",
      type: "text",
      content: "&",
      position: { x: 540, y: 378, width: 120, height: 40 },
      style: {
        fontSize: 28,
        fontFamily: JICF_FONTS.elegant,
        fontWeight: "bold",
        color: JICF_COLORS.gold,
        textAlign: "center",
      },
    },
    {
      id: "groom-label",
      type: "text",
      content: "GROOM",
      position: { x: 670, y: 346, width: 420, height: 20 },
      style: {
        fontSize: 12,
        fontFamily: JICF_FONTS.secondary,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "center",
        letterSpacing: "3px",
      },
    },
    {
      id: "groom-name",
      type: "text",
      content: "{{groomName}}",
      position: { x: 670, y: 368, width: 420, height: 62 },
      style: {
        fontSize: 26,
        fontFamily: JICF_FONTS.script,
        fontWeight: "bold",
        fontStyle: "italic",
        color: JICF_COLORS.secondary,
        textAlign: "center",
      },
    },
    {
      id: "covenant-text",
      type: "text",
      content: "{{covenantText}}",
      position: { x: 90, y: 456, width: 1020, height: 70 },
      style: {
        fontSize: 14,
        fontFamily: JICF_FONTS.primary,
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
        lineHeight: 1.45,
      },
    },
    {
      id: "officiant-heading",
      type: "text",
      content: "OFFICIANT VERIFICATION",
      position: { x: 80, y: 536, width: 420, height: 22 },
      style: {
        fontSize: 13,
        fontFamily: JICF_FONTS.secondary,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "left",
        letterSpacing: "1px",
      },
    },
    {
      id: "officiant-testimony",
      type: "text",
      content:
        "I hereby solemnly testify that this marriage ceremony has been legally and spiritually performed by me.",
      position: { x: 80, y: 560, width: 420, height: 40 },
      style: {
        fontSize: 12,
        fontFamily: JICF_FONTS.primary,
        color: JICF_COLORS.black,
        textAlign: "left",
        lineHeight: 1.35,
      },
    },
    {
      id: "officiant-name",
      type: "text",
      content: "Pastor (Officiant): {{officiantName}}",
      position: { x: 80, y: 604, width: 420, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: JICF_FONTS.elegant,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "left",
      },
    },
    {
      id: "officiant-sig-line",
      type: "rectangle",
      content: "",
      position: { x: 80, y: 662, width: 360, height: 2 },
      style: { backgroundColor: JICF_COLORS.primary },
    },
    {
      id: "officiant-sig-label",
      type: "text",
      content: "Signature & Date",
      position: { x: 80, y: 668, width: 360, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: JICF_FONTS.secondary,
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "left",
      },
    },
    {
      id: "witness-heading",
      type: "text",
      content: "WITNESS TESTIFICATION",
      position: { x: 540, y: 536, width: 580, height: 22 },
      style: {
        fontSize: 13,
        fontFamily: JICF_FONTS.secondary,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "left",
        letterSpacing: "1px",
      },
    },
    {
      id: "witness-testimony",
      type: "text",
      content:
        "We, the undersigned witnesses, were present at this holy wedding ceremony and confirm the authenticity of this marriage covenant.",
      position: { x: 540, y: 560, width: 580, height: 40 },
      style: {
        fontSize: 12,
        fontFamily: JICF_FONTS.primary,
        color: JICF_COLORS.black,
        textAlign: "left",
        lineHeight: 1.35,
      },
    },
    {
      id: "witness1-name",
      type: "text",
      content: "Witness 1: {{witness1Name}}",
      position: { x: 540, y: 604, width: 260, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: JICF_FONTS.elegant,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "left",
      },
    },
    {
      id: "witness1-sig-line",
      type: "rectangle",
      content: "",
      position: { x: 540, y: 662, width: 240, height: 2 },
      style: { backgroundColor: JICF_COLORS.primary },
    },
    {
      id: "witness1-sig-label",
      type: "text",
      content: "Signature & Date",
      position: { x: 540, y: 668, width: 240, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: JICF_FONTS.secondary,
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "left",
      },
    },
    {
      id: "witness2-name",
      type: "text",
      content: "Witness 2: {{witness2Name}}",
      position: { x: 830, y: 604, width: 280, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: JICF_FONTS.elegant,
        fontWeight: "bold",
        color: JICF_COLORS.primary,
        textAlign: "left",
      },
    },
    {
      id: "witness2-sig-line",
      type: "rectangle",
      content: "",
      position: { x: 830, y: 662, width: 250, height: 2 },
      style: { backgroundColor: JICF_COLORS.primary },
    },
    {
      id: "witness2-sig-label",
      type: "text",
      content: "Signature & Date",
      position: { x: 830, y: 668, width: 250, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: JICF_FONTS.secondary,
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "left",
      },
    },
    {
      id: "certificate-id",
      type: "text",
      content: "Certificate ID: {{certificateId}}",
      position: { x: 80, y: 760, width: 1040, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: JICF_FONTS.secondary,
        color: JICF_COLORS.darkGray,
        textAlign: "center",
      },
    },
  ],
  pageSettings: {
    width: 1200,
    height: 838,
    orientation: "landscape",
    backgroundColor: IVORY,
    margin: { top: 16, right: 16, bottom: 16, left: 16 },
    background: { color: IVORY },
  },
  variables: {
    brideName: {
      type: "text",
      label: "Bride",
      required: true,
      placeholder: "Ruphine Manaweh Harmon",
      defaultValue: "Ruphine Manaweh Harmon",
    },
    groomName: {
      type: "text",
      label: "Groom",
      required: true,
      placeholder: "Joshua Bosco Barvor",
      defaultValue: "Joshua Bosco Barvor",
    },
    ceremonyDay: {
      type: "text",
      label: "Day",
      required: true,
      placeholder: "26th",
      defaultValue: "26th",
    },
    ceremonyMonth: {
      type: "text",
      label: "Month",
      required: true,
      placeholder: "September",
      defaultValue: "September",
    },
    ceremonyYear: {
      type: "text",
      label: "Year",
      required: true,
      placeholder: "2026",
      defaultValue: "2026",
    },
    location: {
      type: "text",
      label: "Location",
      required: true,
      placeholder: "Hangzhou, China",
      defaultValue: "Hangzhou, China",
    },
    officiantName: {
      type: "text",
      label: "Pastor (Officiant)",
      required: true,
      placeholder: "Joseph Summers",
      defaultValue: "Joseph Summers",
    },
    witness1Name: {
      type: "text",
      label: "Witness 1",
      required: false,
      placeholder: "★",
      defaultValue: "★",
    },
    witness2Name: {
      type: "text",
      label: "Witness 2",
      required: false,
      placeholder: "★",
      defaultValue: "★",
    },
    covenantText: {
      type: "textarea",
      label: "Covenant paragraph",
      required: true,
      defaultValue:
        "The two individuals have willingly entered into the covenant of marriage, promising to love, honor, cherish, and abide with one another, for better or for worse, in sickness and in health, till death do them part, according to the sacred teachings of the Christian faith.",
    },
    certificateId: {
      type: "text",
      label: "Certificate ID",
      required: false,
      placeholder: "JICF-2026-WED-0001-HB",
      defaultValue: "JICF-2026-WED-0001-HB",
    },
  },
};
