export {
  SPEECH_TYPES,
  SPEECH_CRITERIA,
  SCORING,
  SIDE_LABELS,
  SIDE_COLORS,
} from "./config";
export type { SpeechTypeKey, CriteriaDef } from "./config";
export {
  isValidCriteriaScore,
  calcSpeechTotal,
  isSpeechComplete,
  calcJudgeSideTotal,
  determineWinner,
  calcFinalDecision,
  calcCombinedDecision,
  genOTP,
  fmtScore,
} from "./utils";
export {
  registerSchema,
  loginSchema,
  verifySchema,
  forgotSchema,
  resetSchema,
  createEventSchema,
  updateEventSchema,
  createTeamSchema,
  importTeamsSchema,
  assignJudgeSchema,
  createJudgeByEmailSchema,
  createRoundSchema,
  updateRoundSchema,
  submitScoreSchema,
  audienceVoteSchema,
  completeRoundSchema,
  exportFormat,
  safeParse,
  ROLE_HIERARCHY,
  MANAGE_ROLES,
  JUDGE_ROLES,
  hasRole,
  canManage,
  canScore,
} from "./schemas";
export type {
  RegisterInput,
  LoginInput,
  VerifyInput,
  CreateEventInput,
  UpdateEventInput,
  CreateTeamInput,
  ImportTeamsInput,
  AssignJudgeInput,
  CreateJudgeByEmailInput,
  CreateRoundInput,
  UpdateRoundInput,
  SubmitScoreInput,
  AudienceVoteInput,
  RoleName,
} from "./schemas";
