/**
 * JICF Wedding Certificate — landscape official marriage record.
 * Filled defaults: Harmon / Barvor, 26 September 2026, Hangzhou.
 */

import { CertificateTemplate } from "../types";
import { JICF_COLORS } from "./constants";

const C = {
  navy: JICF_COLORS.blue,
  red: JICF_COLORS.red,
  gold: JICF_COLORS.gold!,
  yellow: JICF_COLORS.yellow,
  cream: "#fffde7",
  ivory: "#fffef8",
  dark: "#1a1530",
};

export const jicfWeddingCertificate: CertificateTemplate = {
  id: "jicf-wedding-certificate",
  name: "JICF Wedding Certificate",
  description:
    "Official landscape wedding certificate for Jinan International Christian Fellowship",
  organization: "jicf",
  category: "wedding",
  elements: [
    {
      id: "outer-border",
      type: "shape",
      content: "",
      position: { x: 18, y: 18, width: 1164, height: 802 },
      style: { color: C.navy },
    },
    {
      id: "gold-border",
      type: "shape",
      content: "",
      position: { x: 32, y: 32, width: 1136, height: 774 },
      style: { color: C.gold },
    },
    {
      id: "cream-panel",
      type: "shape",
      content: "",
      position: { x: 40, y: 40, width: 1120, height: 758 },
      style: { color: C.cream },
    },
    {
      id: "inner-panel",
      type: "shape",
      content: "",
      position: { x: 50, y: 50, width: 1100, height: 738 },
      style: { color: C.ivory },
    },
    {
      id: "jicf-logo",
      type: "image",
      content: "/JICF_LOGO1.png",
      position: { x: 72, y: 64, width: 78, height: 78 },
      style: { objectFit: "contain" },
    },
    {
      id: "seal-disc",
      type: "shape",
      content: "",
      position: { x: 1050, y: 64, width: 78, height: 78 },
      style: { color: C.navy, borderRadius: "50%" },
    },
    {
      id: "seal-cross-v",
      type: "shape",
      content: "",
      position: { x: 1084, y: 76, width: 10, height: 54 },
      style: { color: C.gold, borderRadius: "2px" },
    },
    {
      id: "seal-cross-h",
      type: "shape",
      content: "",
      position: { x: 1064, y: 94, width: 50, height: 10 },
      style: { color: C.gold, borderRadius: "2px" },
    },
    {
      id: "org-name",
      type: "text",
      content: "JINAN INTERNATIONAL CHRISTIAN FELLOWSHIP",
      position: { x: 170, y: 70, width: 860, height: 36 },
      style: {
        fontSize: 24,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "center",
        letterSpacing: "1px",
      },
    },
    {
      id: "subtitle",
      type: "text",
      content: "Official Marriage Certification",
      position: { x: 170, y: 108, width: 860, height: 24 },
      style: {
        fontSize: 16,
        fontFamily: "Georgia, serif",
        fontStyle: "italic",
        fontWeight: "bold",
        color: C.red,
        textAlign: "center",
      },
    },
    {
      id: "title",
      type: "text",
      content: "WEDDING CERTIFICATE",
      position: { x: 80, y: 158, width: 1040, height: 46 },
      style: {
        fontSize: 38,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "center",
        letterSpacing: "2px",
      },
    },
    {
      id: "title-rule",
      type: "shape",
      content: "",
      position: { x: 390, y: 210, width: 420, height: 3 },
      style: { color: C.yellow, borderRadius: "2px" },
    },
    {
      id: "certification",
      type: "text",
      content:
        "This is to certify that on the {{ceremonyDay}} day of {{ceremonyMonth}}, {{ceremonyYear}}, a sacred marriage ceremony was solemnly officiated and completed in {{location}}.",
      position: { x: 90, y: 226, width: 1020, height: 48 },
      style: {
        fontSize: 16,
        fontFamily: "Georgia, serif",
        color: C.dark,
        textAlign: "center",
        lineHeight: "1.45",
      },
    },
    {
      id: "oversight",
      type: "text",
      content:
        "The holy matrimony was celebrated under the authority and pastoral oversight of Jinan International Christian Fellowship, uniting the below two persons in lawful and sacred marriage before God and witnesses.",
      position: { x: 90, y: 276, width: 1020, height: 48 },
      style: {
        fontSize: 15,
        fontFamily: "Georgia, serif",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
        lineHeight: "1.45",
      },
    },
    {
      id: "parties-band",
      type: "shape",
      content: "",
      position: { x: 90, y: 334, width: 1020, height: 108 },
      style: { color: "#fff6c8" },
    },
    {
      id: "bride-label",
      type: "text",
      content: "BRIDE",
      position: { x: 110, y: 344, width: 420, height: 20 },
      style: {
        fontSize: 12,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "center",
        letterSpacing: "2px",
      },
    },
    {
      id: "bride-name",
      type: "text",
      content: "{{brideName}}",
      position: { x: 110, y: 366, width: 420, height: 60 },
      style: {
        fontSize: 26,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        fontStyle: "italic",
        color: C.red,
        textAlign: "center",
      },
    },
    {
      id: "parties-and",
      type: "text",
      content: "&",
      position: { x: 540, y: 376, width: 120, height: 40 },
      style: {
        fontSize: 28,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.gold,
        textAlign: "center",
      },
    },
    {
      id: "groom-label",
      type: "text",
      content: "GROOM",
      position: { x: 670, y: 344, width: 420, height: 20 },
      style: {
        fontSize: 12,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "center",
        letterSpacing: "2px",
      },
    },
    {
      id: "groom-name",
      type: "text",
      content: "{{groomName}}",
      position: { x: 670, y: 366, width: 420, height: 60 },
      style: {
        fontSize: 26,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        fontStyle: "italic",
        color: C.red,
        textAlign: "center",
      },
    },
    {
      id: "covenant",
      type: "text",
      content:
        "The two individuals have willingly entered into the covenant of marriage, promising to love, honor, cherish, and abide with one another, for better or for worse, in sickness and in health, till death do them part, according to the sacred teachings of the Christian faith.",
      position: { x: 90, y: 454, width: 1020, height: 68 },
      style: {
        fontSize: 14,
        fontFamily: "Georgia, serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
        lineHeight: "1.45",
      },
    },
    {
      id: "officiant-heading",
      type: "text",
      content: "OFFICIANT VERIFICATION",
      position: { x: 80, y: 534, width: 420, height: 22 },
      style: {
        fontSize: 13,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "left",
        letterSpacing: "1px",
      },
    },
    {
      id: "officiant-testimony",
      type: "text",
      content:
        "I hereby solemnly testify that this marriage ceremony has been legally and spiritually performed by me.",
      position: { x: 80, y: 558, width: 420, height: 40 },
      style: {
        fontSize: 12,
        fontFamily: "Georgia, serif",
        color: C.dark,
        textAlign: "left",
        lineHeight: "1.35",
      },
    },
    {
      id: "officiant-name",
      type: "text",
      content: "Pastor (Officiant): {{officiantName}}",
      position: { x: 80, y: 602, width: 420, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "left",
      },
    },
    {
      id: "officiant-sig-line",
      type: "shape",
      content: "",
      position: { x: 80, y: 660, width: 360, height: 2 },
      style: { color: C.navy },
    },
    {
      id: "officiant-sig-label",
      type: "text",
      content: "Signature & Date",
      position: { x: 80, y: 666, width: 360, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: "Georgia, serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "left",
      },
    },
    {
      id: "witness-heading",
      type: "text",
      content: "WITNESS TESTIFICATION",
      position: { x: 540, y: 534, width: 580, height: 22 },
      style: {
        fontSize: 13,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "left",
        letterSpacing: "1px",
      },
    },
    {
      id: "witness-testimony",
      type: "text",
      content:
        "We, the undersigned witnesses, were present at this holy wedding ceremony and confirm the authenticity of this marriage covenant.",
      position: { x: 540, y: 558, width: 580, height: 40 },
      style: {
        fontSize: 12,
        fontFamily: "Georgia, serif",
        color: C.dark,
        textAlign: "left",
        lineHeight: "1.35",
      },
    },
    {
      id: "witness1-name",
      type: "text",
      content: "Witness 1: {{witness1Name}}",
      position: { x: 540, y: 602, width: 260, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "left",
      },
    },
    {
      id: "witness1-sig-line",
      type: "shape",
      content: "",
      position: { x: 540, y: 660, width: 240, height: 2 },
      style: { color: C.navy },
    },
    {
      id: "witness1-sig-label",
      type: "text",
      content: "Signature & Date",
      position: { x: 540, y: 666, width: 240, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: "Georgia, serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "left",
      },
    },
    {
      id: "witness2-name",
      type: "text",
      content: "Witness 2: {{witness2Name}}",
      position: { x: 830, y: 602, width: 280, height: 22 },
      style: {
        fontSize: 14,
        fontFamily: "Georgia, serif",
        fontWeight: "bold",
        color: C.navy,
        textAlign: "left",
      },
    },
    {
      id: "witness2-sig-line",
      type: "shape",
      content: "",
      position: { x: 830, y: 660, width: 250, height: 2 },
      style: { color: C.navy },
    },
    {
      id: "witness2-sig-label",
      type: "text",
      content: "Signature & Date",
      position: { x: 830, y: 666, width: 250, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: "Georgia, serif",
        fontStyle: "italic",
        color: JICF_COLORS.darkGray,
        textAlign: "left",
      },
    },
    {
      id: "certificate-id",
      type: "text",
      content: "Certificate ID: {{certificateId}}",
      position: { x: 80, y: 756, width: 1040, height: 18 },
      style: {
        fontSize: 11,
        fontFamily: "Georgia, serif",
        color: JICF_COLORS.darkGray,
        textAlign: "center",
      },
    },
  ],
  pageSettings: {
    width: 1200,
    height: 838,
    margin: { top: 16, right: 16, bottom: 16, left: 16 },
    background: { color: C.ivory },
  },
  fonts: [
    { family: "Georgia, serif", variants: ["normal", "bold", "italic"] },
  ],
};
